version: '3'
services:
  node:
    image: node
    build:
     context: .
     dockerfile: Dockerfile
    restart: always
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - postgres
    environment:
      - PORT=4000
      - POSTGRES_HOST=${POSTGRES_HOST_NAME}
    volumes:
      - .:/usr/app
      - ./log:/usr/app/log
    networks:
      - app-network
  postgres:
    image: postgres
    build: ./database
    container_name: ${POSTGRES_HOST_NAME}
    restart: always
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./dbdata:/var/lib/postgresql/data
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
volumes:
  dbdata:
  node_modules:
  log: